/**
 * Root Layout Component
 * 
<<<<<<< HEAD
 * Provides the application shell and common UI elements:
 * - Font configuration (Geist Sans and Mono)
 * - Global styles
 * - Navigation bar
 * - Refresh state management
 * 
 * All pages are rendered within this layout.
 * 
 * @module layout
=======
 * This is the root layout component that wraps all pages in the application.
 * It configures global fonts (Geist Sans and Geist Mono), imports global styles,
 * and sets up the application-wide providers including the RefreshProvider for state management.
 * 
 * @param {Object} props - The component props
 * @param {React.ReactNode} props.children - Child components to be rendered within the layout
 * @returns {JSX.Element} The root HTML structure with configured fonts and providers
>>>>>>> 3b8aea24de1b098229ecff9a0a6d196d69e3f8bf
 */

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { RefreshProvider } from './RefreshContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RefreshProvider>
          <Navbar />
          {children}
        </RefreshProvider>
      </body>
    </html>
  );
}
